### ISSUE TITLE
Non-existent field in existing hash returns undefined instead of null

### ISSUE THREAD

**Issue by isRyven** [yeahoffline/redis-mock#152]
I have stumbled upon an in-compatible behavior, when getting a non-existent field in existing hash returns `undefined` instead of `null`.  `redis` package itself always returns `null` in such case.

Issue happens for obvious reason, and requires additional handling in code:

https://github.com/yeahoffline/redis-mock/blob/d45588b6e2d6ac625d4586e8772743b541ba8c97/lib/hash.js#L17

**Comment by kamiljano** [comment]
what version are you using and what exact method are you calling? I just tried 0.55.0 and when I call 
```
 r.get("does-not-exist", function (err, result) {

      should.not.exist(result);

      done();

    });
```

that gives me a `null`. In fact the test has been there since 2018 and it is passing... so perhaps we're just looking at different methods?

**Comment by isRyven** [comment]
`hget` i thought it was obvious from the provided source link :)

**Comment by kamiljano** [comment]
assume nothing. I'm only just started playing around in this repo :P 
I made a few PRs recently only because I wanted to take this module into use and i encountered bugs... and then I found that there were already reports of them for almost a year and nobody has been working on them. And then I started fixing some of the bugs, but man, this code base clearly hasn't been particularly up to date for the past few years. If you can find the problem, you can probably also fix some of them. Feel free to fork and make things happen! :P

anyway, the fix for your specific problem: https://github.com/yeahoffline/redis-mock/pull/153

**Comment by isRyven** [comment]
Well i would usually do a pr myself, but i just got discouraged by the issue where owners of the repository don't care to merge stuff anymore, happens to often, but thanks for taking care of it!
