### ISSUE TITLE
should have RedisJSON module functionality

### ISSUE THREAD

**Issue by razaellahi** [yeahoffline/redis-mock#157]
redis.addCommand(); is not available, so that we can't add the reJson commands in it.

like:

var redis = require("redis-mock")
var rejson = require('redis-rejson');
rejson(redis);
rclient = redis.createClient();

gives an error "redis.addCommand is not a function" ----- because rejson uses addCommand() to add rejson commands in redis

**Comment by kamiljano** [comment]
fair point. I just wrote a test (amazing it was missing until now) that lists all methods from the real client and makes sure that the mock implements them all and it spit out that this method is still missing. I'll add it as soon as I figure out what addCommand is actually supposed to be doing :D

**Comment by razaellahi** [comment]
Yes sure, basically this mock client should also has the commands for
reJson module, like JSON.GET and JSON.SET e.t.c, thanks

**Comment by kamiljano** [comment]
right. Correct me if I'm wrong, but now that I tried to dig into this, it looks like the library you're importing actually aims to issue non-standard redis commands that work only because you use the RedisJSON as a form of a proxy to the underlying redis and there can be potentially hundreds of possible extensions working in a similar manner and you would like them all to be supported by redis-mock out of the box...

calling `rejson(redis)` in real environment is fairly straight-forward, because the actual logic is not present in the rejson library itself, but on the server. The rejson library essentially just contains an array of strings and adds them one by one via the `addCommand()`. Providing the implementation of all possible extensions of this kind via the mock out-of-the-box just doesn't seem feasible to me. Especially in this case, when we're talking about adding the support for a 3 year old library that is clearly no longer maintained and has an 80th of the users as this mock does... and redis-mock is nowhere near being a particularly popular library.

Having said that, we could discuss some alternatives.
This is the entire content of the library you're trying to import:

```
function addReJSONModule(redis) {
  var cmds = ["json.del", "json.get", "json.mget", "json.set", "json.type", "json.numincrby", "json.nummultby", "json.strappend", "json.strlen", "json.arrappend", "json.arrindex", "json.arrinsert", "json.arrlen", "json.arrpop", "json.arrtrim", "json.objkeys", "json.objlen", "json.debug", "json.forget", "json.resp"];
  
  cmds.forEach(function(aCmd) {
    redis.addCommand(aCmd);
  });
}
module.exports = addReJSONModule;
```

Then `addCommand()` generates several name variations for each of these commands, so that you can call either `client.json_get()`, `client.JSON_GET()`, `client['json.get']()` or `client['JSON.GET']()`.

To optimize your mocking efforts, we could add a special method that would allow you to define what these methods actually do (in a way allowing you to build a local-proxy, just like RedisJSON is a proxy to a real redis).

In the same place where you define that you want to use the redis-mock, you could pre-configure it in a following manner:

```
const mock = require('redis-mock');

mock.addMockCommand({
   'json.set': (client, args, callback) => {
      // your logic here... probably something like: client.set(client, args[0], JSON.stringify(args[1]), callback);
   }
   'json.get': (client, args, callback) => ...
});
```

then `addCommand()` will generate all the commands in a similar manner as the real redis, but will throw an adequate error if you try to call them without specifying the mock implementation.

if you're okay with that, I can make this happen. But yeah, just like you need to import an extension for the redis library to make it work, you would need to manually extend the logic of the mock to simulate the logic of your specific extension

**Comment by razaellahi** [comment]
Thanks for the description,  

I can understand that the `addCommand()` function is not feasible for the mock implementation, because this function only extends the commands in the library but their actual logic is present in the Redis server, and by using
```
const mock = require('redis-mock');
mock.addMockCommand({
   'json.set': (client, args, callback) => {
      // your logic here... probably something like: client.set(client, args[0], JSON.stringify(args[1]), callback);
   }
   'json.get': (client, args, callback) => ...
});
```
In this manner, the user needs to add his custom logic specific to that command, this is also a nice feature, but this is not what I actually need.

I think, I should change the heading of that issue, but my actual concern was to add the `RedisJSON` module functionalities in the `redis-mock` library, 

`RedisJSON` is a module for Redis that allows the user to save and retrieve the data in the form of JSON. https://oss.redislabs.com/redisjson/. It is basically a new data type in Redis like sets and hashes e.t.c and becoming very popular and according to me, Redis is not complete without it.

what I actually want, is to use the JSON data type in `redis-mock`, like

```
const mock = require('redis-mock');

mock.json_set(key, path, obj, callback)=>{});
mock.json_get(key, path, callback)=>{});
```
In the same way as the `node-redis` library has the `json_set` and `json_get` commands after extending it with the `redis-rejson` library. `redis-mock` should already have those commands without extending it.

So in the actual environment, If anyone using `node-redis` with `redis-rejson`, then he can easily change the actual environment with the mock one by just using `redis-mock`.

I think you are familiar with that issue, https://github.com/RedisJSON/RedisJSON/issues/83

`redis-mock` is a very good mock for Redis, but what is missing, is the JSON data type.

Thanks,

**Comment by kamiljano** [comment]
Actually I wasn't familiar with this other reported issue. I became one of the maintainers only 2 weeks ago and so far I've been mostly just cleaning the code base. Still, please note that the redis library does not come with the support for the functionality you're requesting, but instead you have to install it separately. Even redis itself does not come with this functionality. It's an extension that has to be swt up and configured both on the server and the client side. There are potentially many similar extensions out there. That doesn't mean we want the users of redis-mock to download them along with our package just because the real equivalents of these features exist in the wild.

Personally I would rather follow here the philosophy of the redis module developers - make the module extensible through extra modules, but don't pack functionality that is potentially unsupported by your server directly into the main module.

So here i would like to propose the way of extending the redis-mock module, whereas the redis-rejson-mock would have to come as a separate module

**Comment by razaellahi** [comment]
Actually for many users including me, Redis is useless, unless it has
RedisJSON module.

I am using Redis with this module and only using it's JSON data type, I
want to create a mock for it, for unit test purposes and redis-mock is
unable to serve that purpose.

**Comment by kamiljano** [comment]
thank you for sharing, but this is `redis-mock` module. It aims to simulate the behaviour of the `redis` module that targets the integration specifically with Redis, not RedisJSON. Whether Redis is useless in general is arguable and NPM repo gives some real numbers on that. The `redis` module has been downloaded this week 1.8 million times whereas `redis-rejson` has been downloaded... 1.9k times. That's less than 1% of all Node.js redis users. This maintains my belief that more than 99% of all redis users do find it more useful than RedisJSON.

As mentioned before, I don't want to block you, but I don't think `redis-mock` is the right place for the functionality you're looking for. The `redis` module is built to be extensible specifically for this kind of cases and `redis-mock` should be altered to be equally extensible for this functionality. This however means that, just like you need an extra `redis-rejson` module, you would need an extra `redis-rejson-mock` equivalent of it.

**Comment by razaellahi** [comment]
RedisJSON is not an independent component, It is a module that needs to be
integrate with Redis, both server and client side.

At client side, as you know that, node-redis can be integrated with
redis-rejson if addCommand() function is available in node-redis.

Let suppose if redis-rejson-mock will be available in the future,  then how
It can be integrated with redis-mock.

**Comment by kamiljano** [comment]
so this is what I'm talking about here.
In `redis-mock` I would like to provide the implementation of 
* `addMockCommand()` - allows to define the mock behaviour of an extension
* `addCommand()` - in this case would just enable the usage of whatever was preconfigured in `addMockCommand()` but maintain the same interface as the `redis` library to ensure that you cannot use the additional methods until they were set up just like the real ones. 

Then it would be possible to release `redis-rejson-mock` that would depend on these two methods and allow you to set things up with pretty much same amount of effort you currently require to get `redis-mock` in place

**Comment by razaellahi** [comment]
Okay,  then In that case, that would also be nice.

**Comment by kamiljano** [comment]
Closing this issue and replacing it with 2 new ones with clear definition:

* https://github.com/yeahoffline/redis-mock/issues/163
* https://github.com/yeahoffline/redis-mock/issues/164
